### ISSUE TITLE
`float` constants may not take the type of their type expression

### ISSUE THREAD

**Issue by wenooij** [nevalang/neva#495]
**Describe the bug**
When making a floating point constant with no decimal part, the constant is determined to be an integer dispite having the type expression `float` 

**To Reproduce**
main.neva
```
const x float = 1000

component Main(start any) (stop any) {
	nodes {
	}
	net {
		:start -> :stop
	}
}
```

Run `$ neva  build ./src/main.neva` or `run`.

Error:

```
src/main.neva:1:6 Constant cannot have several values at once
```

**Expected behavior**
The type is reinterpreted as a `float`.

** Additional Context **
Note that this could also be fixed by changing line 1 to `const x float = 1000.0`

**Comment by emil14** [comment]
@wenooij fixed https://github.com/nevalang/neva/pull/500 

Thank u much for creating this issue
