### ISSUE TITLE
Exposed Golang nil pointer derefrence

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#503]
**Describe the bug**
You can easily casue a nil pointer derefrence runtime error.

**To Reproduce**
Was testing out some stuff and found this:
```
const array list<int> = [1,2,3]
component Main(start any) (stop any) {
	nodes { printer Printer<any>}
	net {
		:start -> ($array -> printer:data) 
		printer:sig 
	}
}

```

**Expected behavior**
For nevalang to error and not golang exposing itself

**Screenshots**
![image](https://github.com/nevalang/neva/assets/129544899/d07701c1-ed6f-49f4-af05-1a661cac93db)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by emil14** [comment]
@dorian3343 this line 

```neva
printer:sig 
```

Is incorrect. Connection must always have sender and receiver like `printer:sig -> :stop`.

But error messages must be improved for sure.

**Comment by emil14** [comment]
@dorian3343 https://github.com/nevalang/neva/releases/tag/v0.10.2 fixed

thanks
