### ISSUE TITLE
Token error with negative number inside list

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#516]
Neva throws an error when you try to place a negative number in a list
**Code**
```
const n list<int> = [-215]
component Main(start any) (stop any) {
	nodes {
	    printer Printer<any>
	    len Len<list<int>>
	}
	net {
		:start -> ($n -> len:data)
	       len:res -> printer:data
		printer:sig -> :stop
	}
}
```

**Error**
```
//.neva:0:0 1:21 token recognition error at: '-2'
```
![Screenshot from 2024-03-13 10-08-33](https://github.com/nevalang/neva/assets/129544899/6ab465eb-c601-4edc-ae82-ed188cf76b9f)

**Comment by emil14** [comment]
Thanks

Fixed in https://github.com/nevalang/neva/releases/tag/v0.10.5
