### ISSUE TITLE
Ugly error message in wrong type for nodes

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#517]
When using a component that expects a `List<T any>` and you put just `any` as the Type for the node you receive an ugly pointer error message.

**Code**
```
const n list<int> = [215,112]
component Main(start any) (stop any) {
	nodes {
	    printer Printer<any>
	    len Len<any>
	}
	net {
		:start -> ($n -> len:data)
	    len:res -> printer:data
		printer:sig -> :stop
	}
}
```
**Error**
```
std@0.10.4/builtin/base.neva:5:5 Subtype must be subtype of supertype union: want [{<nil> 0xc000037560 <nil>} {<nil> 0xc0000375f0 <nil>}], got {<nil> 0xc0000374d0 <nil>}
```

**Screenshot**
![image](https://github.com/nevalang/neva/assets/129544899/19b717f1-b776-424a-bc07-7a82203faca7)

**Comment by emil14** [comment]
Fixed https://github.com/nevalang/neva/pull/519
