### ISSUE TITLE
Floats are possible broken

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#537]
During working on the **List Sort** stdlib component I discovered that floats seemingly don't work.
When trying to do anything with them, we receive <empty>

Example code:
![image](https://github.com/nevalang/neva/assets/129544899/bd64868f-ba9b-4c2b-912d-133d9dacfa6f)

Output:
![image](https://github.com/nevalang/neva/assets/129544899/cec67cb8-ce9b-46cb-9316-bfb045956312)

This is also an occurance when you use float instead of any and when you use just a float value instead of an array. 
![image](https://github.com/nevalang/neva/assets/129544899/8b5c2a10-d1de-4695-b334-7faffea91b4c)

![image](https://github.com/nevalang/neva/assets/129544899/fb44b063-989c-4375-be04-dd861497cbb6)

**Comment by emil14** [comment]
fix #538
