### ISSUE TITLE
Reference an enum in a imported package

### ISSUE THREAD

**Issue by Catya3** [nevalang/neva#560]
**Describe the bug**

What's the correct way to refer to an enum in a imported package?

Ex.

```
pub type Format enum {
  Raw,
  PNG,
  JPEG
}
```

```
import ( image )
...
image::Format::PNG -> image:fmt  // causes panic
...
```

```
invalid memory address or nil pointer dereference: goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/nevalang/neva/internal/compiler/parser.Parser.parseFile.func1()
        /home/$USER/src/github.com/Catya3/neva/internal/compiler/parser/parser.go:112 +0xe5
panic({0xad8900?, 0x11d7bd0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/nevalang/neva/internal/compiler/parser.parseNormConn({0xcd9708, 0xc0004a7600}, {{0xc0001c4a60, 0xf}, {0xf, 0x7}, {0xf, 0x14}})
        /home/$USER/src/github.com/Catya3/neva/internal/compiler/parser/net.go:133 +0x576
```

Neither other obvious way to qualify the enum works (`image.Format::`, or `image.Format.`)

**To Reproduce**
1. Make an enum in stdlib for instance, or another package
2. Import the package
3. Try to qualify  the enum alternative

**Expected behavior**
There is a way to use enums in another package.

**Comment by emil14** [comment]
Sorry for that. Will fix

**Comment by emil14** [comment]
```neva
import { x }

component Main(start) (stop) {
    nodes { Println }
    net { :start -> (x.Format::Png -> println) }
}
```

This is my code and this is what I got

```log
tmp/main.neva:5:21 can't get type def from scope by ref: entity not found: 'Format'
```

I mean it's not panic. But errors must be fixed tho

**Comment by emil14** [comment]
@Catya3 couldn't repro, here's my code, output is `0`

```neva
import { x }

component Main(start) (stop) {
    nodes { Println }
    net { :start -> (x.Format::Raw -> println -> :stop) }
}
```

I've defined `Format` in `x` like this

```neva
pub type Format enum {
  Raw,
  PNG,
  JPEG
}
```

However I've found another issue #562 

Also please note that now you have to `rm -rf ~/neva` after _any_ change in `std` (so compiler can write new std to disk, it won't do that if there's std already). I'm thinking about how to optimize this DX right now.

**Comment by Catya3** [comment]
Confirmed the issue was due to unclean Neva std directory. My bad!

**Comment by Catya3** [comment]
Done!
