### ISSUE TITLE
Allow interfaces with anonymous ports

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#604]
In this case we don't care about the port names. It could make sense to allow any component where count ports and their type matches to implement this interface

```
IHandler(any) (any)

...

... -> iHandler -> ...
```

**Comment by Catya3** [comment]
Is it possible to analyze code without port names currently or would this be a new mode of analysis?

**Comment by emil14** [comment]
I just figured out that this could only be possible for interfaces. Components must always provide some port names even if there's 1 in/outport. The reason is that we need to somehow refer to our own ports in the network.

Ofc it could be possible to have empty strings as port names and refer to them like `:->:` but looks weird. Feels safer to avoid this.

**Comment by emil14** [comment]
> Is it possible to analyze code without port names currently or would this be a new mode of analysis?

Analyzer will need some fixes if we will allow this but it's not rocket science :)

**Comment by emil14** [comment]
That could even be a enforced rule not to have port names for interfaces with one port on a side, that makes easier to implement that interface and makes code harder to broke after renaming stuff

**Comment by emil14** [comment]
I've looked at this today and figure out it's not possible with existing desugarer and instead only at IR stage

When we desugar component we don't know who uses it. More than that, it might be used in several places, including other modules that will be dependent on.

So desugarer simply can't replace `""` port in network sender/receiver because it has no idea what should be set instead
