### ISSUE TITLE
[Idea]: Partial structural matching

### ISSUE THREAD

**Issue by Catya3** [nevalang/neva#609]
In a structural type system I should expect to use `Match<stream<int>>` to do this:

```
... -> match:data // pass stream to data
{last: true} -> match:case[0] -> :stop
```

That is it should match on the partial contents of the struct. What I actually got is:

{"data": 50, "idx": 0, "last": true}
panic: runtime error: comparing uncomparable type runtime.MapMsg

**Comment by emil14** [comment]
Seems like both `Eq` (if we gonna have one) and `Match` should implement this

**Comment by emil14** [comment]
@Catya3 is this how Rust works?

```
{last: true} -> match:case[0] -> :stop
```

**Comment by emil14** [comment]
@Catya3 do we need this issue if we have https://github.com/nevalang/neva/issues/613 ?

Is this issue about something else except structures? Is (partial) pattern matching working in e.g. Rust for smt else?
