### ISSUE TITLE
[Idea]: Replace `=` with `<-` the "assignment operator"

### ISSUE THREAD

**Issue by Catya3** [nevalang/neva#610]
In all cases we use `=` I believe it's more on brand to adopt the backwards arrow `<-` the assignment operator.

It's more on brand for a flow based language with no variables.

## Before

```
const x int = 50

component Foo(x int = 50) (y int)
```

## After

```
const x int <- 50

component Foo(x int <- 50) (y int)
```

This will be a simple find and replace.

**Comment by dorian3343** [comment]
Im personally against this, it introduces nothing new and makes new users confused. Everyone knows what `=` means and changing it just because is counter-productive.

**Comment by emil14** [comment]
@Catya3 even though I like it and can feel how it semantically closer to what's actually happening, I agree with @dorian3343 that it will confuse new users.

I'm gonna close this one but please now that I like it :)
