### ISSUE TITLE
Merge strconv and string in std

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#616]
Having two packages is pointless since strconv and strings overlap and can be just merged into strings.

**Comment by emil14** [comment]
I followed Go's stdlib structure, they have `strconv` as a separate package.

I believe the idea is to have separate package for conversions while `strings` contains string _manipulations_.

However it's not something I'm 100% sure about (that was the reason I followed the Go's approach), so issue can remain open. Let's see what others think

**Comment by emil14** [comment]
I think we should mimic Go where possible
