### ISSUE TITLE
Update `neva new` for the removal of `net` keyword

### ISSUE THREAD

**Issue by Catya3** [nevalang/neva#618]
**Describe the bug**
`neva new` generates code using the `net` keyword.

**To Reproduce**
1. Start a new project
2. Call `neva run src`
3. See error

```
3:1 extraneous input 'net'
```

**Comment by emil14** [comment]
@Catya3 thanks! 

Fixed in https://github.com/nevalang/neva/pull/621

I'll also add e2e test for this in #619
