### ISSUE TITLE
`Zip` component

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#640]
# Fixed (2 inputs)

```neva
type ZipResult<T, Y> {
  first T 
  second Y
}

pub component Zip<T, Y>(first stream<T>, second stream<Y>) (res stream<ZipResult<T, Y>>)
```

## Upsides

- type-safe
- easy to use

## Downsides

- support only 2 streams

# Variadic (N inputs)

```neva
pub component Zip<T>([streams] stream<T>) (res stream<T>)
```

## Upsides

- supports N (up to 255) streams

## Downsides

- might be a bit harder to use (questionable, less generics)
- stream items must be of the same type (can't e.g. merge int with string, etc)

# A Note On Stream Size

We have to decide how to handle streams of different length (size)

I suggest follow how Python does it - finish when first stream is ended. Elements of other stream(s) are simply immited (TODO check if that's true, is Python really like this?)

**Comment by Catya3** [comment]
Seems like Python would take the shorter of the two
```
>>> x=[1,2,3,4]
>>> y=[1,2,3]
>>> list(zip(x,y))
[(1, 1), (2, 2), (3, 3)]
```

**Comment by emil14** [comment]
Done by @Catya3
