### ISSUE TITLE
Iter should support strings

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#643]
Should be a way to stream list of chars

**Comment by dorian3343** [comment]
Just use split and iter, no point in adding overloading to solve a rare case (IMO)

**Comment by emil14** [comment]
1. that's inefficient - we create array under the hood just to stream it
2. what problem are we solving by not implementing overload? it's easy to implement and it's easier to use one component instead of two

**Comment by emil14** [comment]
I'm not sure it's possible from type-system perspective though

**Comment by emil14** [comment]
there's no Iter now
