### ISSUE TITLE
Force Outport Operator

### ISSUE THREAD

**Issue by dorian3343** [nevalang/neva#645]
Create an operator that would force an Outport to be used.

This would prevent misusing component's and prevent Error's not being handled. We could implement `else` for match l and Fatal Errors like this.

**Comment by emil14** [comment]
@dorian3343 did you see #582 ?

**Comment by emil14** [comment]
Please look at that issue, if these are duplicates let's close this one and continue there

**Comment by dorian3343** [comment]
Didn't see that issue, closing
